INSERT INTO televisions (type,
                         brand,
                         name,
                         price,
                         available_size,
                         refresh_rate,
                         screen_type,
                         screen_quality,
                         smart_tv,
                         wifi,
                         voice_control,
                         hdr,
                         bluetooth,
                         ambi_light,
                         original_stock,
                         sold)
VALUES ('big ONE',
        'Sony',
        'boob tube',
        2000,
        400,
        60,
        'oled',
        'hd',
        true,
        true,
        true,
        true,
        true,
        true,
        20,
        10);

INSERT INTO users (username, password, enabled, email)
VALUES ('ben', '$2a$12$5CZNfchW.KoDGIf0/8SMpeHfRU.Qlki28RUCYddJhWqzBJ7mLCcIe', true, 'ben@techiteasy.nl'),
        ('ellen', '$2a$12$5CZNfchW.KoDGIf0/8SMpeHfRU.Qlki28RUCYddJhWqzBJ7mLCcIe', true, 'ellen@techiteasy.nl'),
        ('bob', '$2a$12$5CZNfchW.KoDGIf0/8SMpeHfRU.Qlki28RUCYddJhWqzBJ7mLCcIe', true, 'bob@techiteasy.nl'),
        ('saskia', '$2a$12$5CZNfchW.KoDGIf0/8SMpeHfRU.Qlki28RUCYddJhWqzBJ7mLCcIe', true, 'saskia@techiteasy.nl');

INSERT INTO roles (username, role)
VALUES ('ben', 'ROLE_ADMIN'),
        ('ben', 'ROLE_USER'),
        ('ellen', 'ROLE_USER'),
        ('bob', 'ROLE_USER'),
        ('saskia', 'ROLE_USER');