INSERT INTO televisions (type,
                         brand,
                         name,
                         price,
                         available_size,
                         refresh_rate,
                         screen_type,
                         screen_quality,
                         smart_tv,
                         wifi,
                         voice_control,
                         hdr,
                         bluetooth,
                         ambi_light,
                         original_stock,
                         sold)
VALUES ('big',
        'Sony',
        'boob tube',
        2000,
        400,
        60,
        'oled',
        'hd',
        true,
        true,
        true,
        true,
        true,
        true,
        20,
        10);